//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_RUSUARIO
    {
        public TBL_RUSUARIO()
        {
            this.TBL_RAUDITORIA = new HashSet<TBL_RAUDITORIA>();
            this.TBL_UUSUARIO_PERFIL = new HashSet<TBL_UUSUARIO_PERFIL>();
        }
    
        public long USU_NID { get; set; }
        public Nullable<long> EMP_NID { get; set; }
        public string USU_CUSUARIO { get; set; }
        public string USU_CCLAVE { get; set; }
        public bool USU_OESTADO { get; set; }
    
        public virtual ICollection<TBL_RAUDITORIA> TBL_RAUDITORIA { get; set; }
        public virtual TBL_REMPLEADO TBL_REMPLEADO { get; set; }
        public virtual ICollection<TBL_UUSUARIO_PERFIL> TBL_UUSUARIO_PERFIL { get; set; }
    }
}
