//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_RCOMPANIA
    {
        public TBL_RCOMPANIA()
        {
            this.TBL_REMPLEADO = new HashSet<TBL_REMPLEADO>();
        }
    
        public long COM_NID { get; set; }
        public string COM_CNOMBRE { get; set; }
        public bool COM_OESTADO { get; set; }
    
        public virtual ICollection<TBL_REMPLEADO> TBL_REMPLEADO { get; set; }
    }
}
