//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_RPERFIL
    {
        public TBL_RPERFIL()
        {
            this.TBL_UUSUARIO_PERFIL = new HashSet<TBL_UUSUARIO_PERFIL>();
        }
    
        public long PER_NID { get; set; }
        public string PER_CDESCRIPCION { get; set; }
        public bool PER_OESTADO { get; set; }
    
        public virtual ICollection<TBL_UUSUARIO_PERFIL> TBL_UUSUARIO_PERFIL { get; set; }
    }
}
