//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_RTIPO_IDENTIFICACION
    {
        public TBL_RTIPO_IDENTIFICACION()
        {
            this.TBL_REMPLEADO = new HashSet<TBL_REMPLEADO>();
        }
    
        public long TID_NID { get; set; }
        public string TID_CDESCRIPCION { get; set; }
        public bool TID_OESTADO { get; set; }
    
        public virtual ICollection<TBL_REMPLEADO> TBL_REMPLEADO { get; set; }
    }
}
