//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_UUSUARIO_PERFIL
    {
        public long UUP_NID { get; set; }
        public long USU_NID { get; set; }
        public long PER_NID { get; set; }
        public bool UUP_OESTADO { get; set; }
    
        public virtual TBL_RPERFIL TBL_RPERFIL { get; set; }
        public virtual TBL_RUSUARIO TBL_RUSUARIO { get; set; }
    }
}
