//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_REMPLEADO
    {
        public TBL_REMPLEADO()
        {
            this.TBL_RUSUARIO = new HashSet<TBL_RUSUARIO>();
        }
    
        public long EMP_NID { get; set; }
        public long TID_NID { get; set; }
        public long COM_NID { get; set; }
        public string EMP_CIDENTIFICACION { get; set; }
        public string EMP_CNOMBRES { get; set; }
        public string EMP_CAPELLIDOS { get; set; }
        public System.DateTime EMP_DFECHA_NACIMIENTO { get; set; }
    
        public virtual TBL_RCOMPANIA TBL_RCOMPANIA { get; set; }
        public virtual TBL_RTIPO_IDENTIFICACION TBL_RTIPO_IDENTIFICACION { get; set; }
        public virtual ICollection<TBL_RUSUARIO> TBL_RUSUARIO { get; set; }
    }
}
